name: Bass Fishing Board Game
favicon: null
layout_spectrum: 0.89383
typography_spectrum: 0.79717
title: Bass Fishing Board Game
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77808600-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfbf7'
    - '#c4bfbb'
    - '#918376'
    - '#170f02'
    - '#b34032'
  brandStrength: 0.9375
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
