name: Bass Fishing Board Game
favicon: null
layout_spectrum: 0.391526794526726
typography_spectrum: 0.13876
title: Bass Fishing Board Game
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77808600-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#a09fa0'
    - '#36414a'
    - '#abb822'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 1
purpose: []
