name: Bass Fishing Board Game
favicon: null
layout_spectrum: 0.23456
typography_spectrum: 0.79717
title: Bass Fishing Board Game
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77808600-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0000'
    - '#7d0000'
    - '#ff7600'
    - '#ffca00'
  brandStrength: 0.9375
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
