name: Bass Fishing Board Game
favicon: null
layout_spectrum: 0.391526794526726
typography_spectrum: 0.39124504826031625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08110381476581097
  lightness: 0.3490130149293691
  saturation: 0.47471184912137687
  rhythmicContrast: 0.9537484415341169
purpose: []
