name: Bass Fishing Board Game
favicon: null
layout_spectrum: 0.63272
typography_spectrum: 0.31302
title: Bass Fishing Board Game
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77808600-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9ac0d5'
    - '#a19505'
    - '#6c6a6b'
  brandStrength: 1
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
