name: Bass Fishing Board Game
favicon: null
layout_spectrum: 0.80535
typography_spectrum: 0.74192
title: Bass Fishing Board Game
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77808600-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#f69a25'
    - '#9d000d'
    - '#335ee5'
  brandStrength: 0.9375
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0
purpose: []
