typography_spectrum: 0.31302
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9ac0d5'
    - '#a19505'
    - '#6c6a6b'
  brandStrength: 1
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.63272
analytics:
  google: UA-77808600-1
  facebook: "<!-- Facebook Pixel Code --> <script> !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod? n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n; n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0; t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window, document,'script','https://connect.facebook.net/en_US/fbevents.js');  fbq('init', '280094229001171'); fbq('track', \"PageView\");</script> <noscript><img height=\"1\" width=\"1\" style=\"display:none\" src=\"https://www.facebook.com/tr?id=280094229001171&ev=PageView&noscript=1\" /></noscript> <!-- End Facebook Pixel Code -->"
  twitter: null
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/5ee47117-fda9-493f-b916-fdd17456610b.png'
name: Bass Fishing Board Game
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ff09b49-b425-46b3-a247-1d9307e1f993.png'
title: Bass Fishing Board Game
purpose: []
